version: 2.1
jobs:
  build:
    working_directory: /front-simple
    docker:
      - image: kellydouglass/front-simple
      auth:
        username: $DOCKERHUB_USER 
        password: $DOCKERHUB_PASS

    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm test
